### ISSUE TITLE
SystemTextJsonScalyrFormatter fails when serializing log events with Exceptions

### ISSUE THREAD

**Issue by llaughlin** [TinyBlueRobots/Serilog.Sinks.Scalyr#2]
If a `LogEvent` contains an `Exception` that has a `TargetSite` property set, the `SystemTextJsonScalyrFormatter` throws an exception when it tries to serialize the `Exception`:
> `System.NotSupportedException`: Serialization and deserialization of 'System.IntPtr' instances are not supported. Path: $.TargetSite.MethodHandle.Value.

https://github.com/dotnet/runtime/issues/43026 contains a couple workarounds that may work.

**Comment by JonCanning** [comment]
I'm tidying up this project for the NET6 version, including removing Newtonsoft, and I'm wondering if this is still needed? I've tried writing a test that covers `IntPtr` and it works, so I'm wondering if you have any insight into how I could ensure that I don't introduce a regression? Thanks!
